Entity/Directories.php
<?php

namespace CMS\ContentBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Directories
 */
class Directories
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var integer
     */
    private $parent;

    /**
     * @var
     */
    private $children;

    /**
     * @var string
     */
    private $title;

    /**
     * @var string
     */
    private $alias;

    /**
     * @var string
     */
    private $keywords;

    /**
     * @var string
     */
    private $description;

    /**
     * @var boolean
     */
    private $is_published = true;

    /**
     * @var boolean
     */
    private $is_deleted = false;

    /**
     * @var integer
     */
    private $create_by;

    /**
     * @var integer
     */
    private $update_by;

    /**
     * @var \DateTime
     */
    private $date_create;

    /**
     * @var \DateTime
     */
    private $date_update;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set parent
     *
     * @param integer $parent
     * @return Directories
     */
    public function setParent($parent)
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * Get parent
     *
     * @return integer
     */
    public function getParent()
    {
        return $this->parent;
    }

    /**
     * @return mixed
     */
    public function getChildren()
    {
        return $this->children;
    }

    /**
     * @param mixed $children
     */
    public function setChildren($children)
    {
        $this->children = $children;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Directories
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @return string
     */
    public function getAlias()
    {
        return $this->alias;
    }

    /**
     * @param string $alias
     * @return Directories
     */
    public function setAlias($alias)
    {
        $this->alias = $alias;

        return $this;
    }

    /**
     * Set keywords
     *
     * @param string $keywords
     * @return Directories
     */
    public function setKeywords($keywords)
    {
        $this->keywords = $keywords;

        return $this;
    }

    /**
     * Get keywords
     *
     * @return string
     */
    public function getKeywords()
    {
        return $this->keywords;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Directories
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set is published
     *
     * @param boolean $is_published
     * @return Directories
     */
    public function setIsPublished($is_published)
    {
        $this->is_published = $is_published;

        return $this;
    }

    /**
     * Get is published
     *
     * @return boolean
     */
    public function getIsPublished()
    {
        return $this->is_published;
    }

    /**
     * Set is deleted
     *
     * @param boolean $is_deleted
     * @return Directories
     */
    public function setIsDeleted($is_deleted)
    {
        $this->is_deleted = $is_deleted;

        return $this;
    }

    /**
     * Get is deleted
     *
     * @return boolean
     */
    public function getIsDeleted()
    {
        return $this->is_deleted;
    }

    /**
     * Set create by
     *
     * @param integer $create_by
     * @return Directories
     */
    public function setCreateBy($create_by)
    {
        $this->create_by = $create_by;

        return $this;
    }

    /**
     * Get create by
     *
     * @return integer
     */
    public function getCreateBy()
    {
        return $this->create_by;
    }

    /**
     * Set update by
     *
     * @param integer $update_by
     * @return Directories
     */
    public function setUpdateBy($update_by)
    {
        $this->update_by = $update_by;

        return $this;
    }

    /**
     * Get update by
     *
     * @return integer
     */
    public function getUpdateBy()
    {
        return $this->update_by;
    }

    /**
     * Set date create
     *
     * @param \DateTime $date_create
     * @return Directories
     */
    public function setDateCreate($date_create)
    {
        $this->date_create = new \DateTime();

        return $this;
    }

    /**
     * Get date create
     *
     * @return \DateTime
     */
    public function getDateCreate()
    {
        return $this->date_create;
    }

    /**
     * Set date update
     *
     * @param \DateTime $date_update
     * @return Directories
     */
    public function setDateUpdate($date_update)
    {
        $this->date_update = new \DateTime();

        return $this;
    }

    /**
     * Get date update
     *
     * @return \DateTime
     */
    public function getDateUpdate()
    {
        return $this->date_update;
    }
}

Form/ContentType.php
<?php

namespace CMS\ContentBundle\Form;

use CMS\ContentBundle\Form\Types\StylesType;
use CMS\LocalizationBundle\Form\Types\LocaleEntityType;
use CMS\LocalizationBundle\Form\Types\LocaleTextareaType;
use CMS\LocalizationBundle\Form\Types\LocaleTextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ContentType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('parent', LocaleEntityType::class, array(
                'class' => 'ContentBundle:Directories',
                'choice_label' => 'title',
                'empty_data' => null,
                'placeholder' => '',
                'required' => false
            ))
            ->add('title', LocaleTextType::class)
            ->add('alias')
            ->add('keywords', LocaleTextareaType::class, array(
                'required' => false
            ))
            ->add('description', LocaleTextareaType::class, array(
                'required' => false
            ))
            ->add('introduction', LocaleTextareaType::class, array(
                'required' => false,
                'attr' => array('class' => 'tinyMce')
            ))
            ->add('content', LocaleTextareaType::class, array(
                'attr' => array('class' => 'tinyMce')
            ))
            ->add('styles', StylesType::class)
            ->add('rating', IntegerType::class)
            ->add('is_main')
            ->add('is_published')
            ->add('is_deleted');
    }

    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'CMS\ContentBundle\Entity\Content',
            'translation_domain' => 'systems'
        ));
    }

    /**
     * @return string
     */
    public function getBlockPrefix()
    {
        return 'cms_contentbundle_content';
    }
}

Controller/ContentController.php
<?php

namespace CMS\ContentBundle\Controller;

use CMS\ContentBundle\Response\ContentJsonResponse;
use Doctrine\DBAL\DBALException;
use Pegas\ContentBundle\Response\ErrorJsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

/**
 * Class ContentController
 * @package CMS\ContentBundle\Controller
 */
class ContentController extends Controller
{
    /**
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function listAction()
    {
        $serviceContent = $this->get('cms.content.content.service');
        $serviceDirectories = $this->get('cms.content.directories.service');

        return $this->render('ContentBundle:Content:list.html.twig', array(
            'contents' => $serviceContent->findAll(),
            'directories' => $serviceDirectories->findAll()
        ));
    }

    /**
     * @param Request $request
     * @param $parent
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     */
    public function createAction(Request $request, $parent)
    {
        $service = $this->get('cms.content.content.service');

        $form = $service->generateForm();

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $data = $form->getData();
                $data->setParent($parent);
                $data->setCreateBy($this->getUser()->getId());

                $service->create($data);

                return $this->redirect($this->generateUrl('cms_content_list'));
            }
        }

        return $this->render('ContentBundle:Content:edit.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @param Request $request
     * @param $id
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     */
    public function editAction(Request $request, $id)
    {
        $service = $this->get('cms.content.content.service');

        $form = $service->generateForm($service->findOneById($id));

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $data = $form->getData();

                $service->update($data);

                return $this->redirect($this->generateUrl('cms_content_list'));
            }
        }

        return $this->render('ContentBundle:Content:edit.html.twig', array(
            'form' => $form->createView()
        ));
    }

    /**
     * @param Request $request
     * @return ContentJsonResponse
     */
    public function ajaxGetAction(Request $request)
    {
        $id = $request->get('id');
        $service = $this->get('cms.content.content.service');

        if (null !== $id) {
            $result = $service->findOneById($id);
        } else {
            $result = $service->findAll();
        }

        return new ContentJsonResponse($result);
    }

    /**
     * @param Request $request
     * @return ContentJsonResponse|ErrorJsonResponse
     */
    public function ajaxChangeStatusAction(Request $request)
    {
        $id = $request->get('id');
        $status = $request->get('status', false);
        $service = $this->get('cms.content.content.service');

        $content = $service->findOneById($id);

        if (!$content) {
            return new ErrorJsonResponse(sprintf('Content of ID \'%s\' not found!', $id));
        }

        $content->setIsPublished(filter_var($status, FILTER_VALIDATE_BOOLEAN));

        try {
            $service->update($content);
        } catch (DBALException $e) {
            return new ErrorJsonResponse($e->getMessage());
        }

        return new ContentJsonResponse(array('status' => 'ok', 'message' => 'The operation completed successfully'));
    }

    /**
     * @param Request $request
     * @return ContentJsonResponse|ErrorJsonResponse
     */
    public function ajaxDeleteAction(Request $request)
    {
        $id = $request->get('id');
        $service = $this->get('cms.content.content.service');

        $content = $service->findOneById($id);

        if (!$content) {
            return new ErrorJsonResponse(sprintf('Content of ID \'%s\' not found!', $id));
        }

        try {
            $content->setIsDeleted(true);
            $service->update($content);
        } catch (DBALException $e) {
            return new ErrorJsonResponse($e->getMessage());
        }

        return new ContentJsonResponse(array('status' => 'ok', 'The operation completed successfully'));
    }

    /**
     * @param Request $request
     * @return ContentJsonResponse|ErrorJsonResponse
     */
    public function ajaxRestoreAction(Request $request)
    {
        $id = $request->get('id');
        $service = $this->get('cms.content.content.service');

        $content = $service->findOneById($id);

        if (!$content) {
            return new ErrorJsonResponse(sprintf('Content of ID \'%s\' not found!', $id));
        }

        try {
            $content->setIsDeleted(false);
            $service->update($content);
        } catch (DBALException $e) {
            return new ErrorJsonResponse($e->getMessage());
        }

        return new ContentJsonResponse(array('status' => 'ok', 'The operation completed successfully'));
    }

    /**
     * @param Request $request
     * @return ContentJsonResponse|ErrorJsonResponse
     */
    public function ajaxSaveAction(Request $request)
    {
        $service = $this->get('cms.content.content.service');

        $id = $request->get('id');
        $title = $request->get('title');
        $content = $request->get('content');

        if (empty($title)) {
            return new ErrorJsonResponse(sprintf('Field "Title" is required!'));
        }

        if (empty($content)) {
            return new ErrorJsonResponse(sprintf('Field "Content" is required!'));
        }

        $newObject = new \CMS\ContentBundle\Entity\Content();

        if (null !== $id) {
            $newObject = $service->findOneById($id);
        }

        $newObject->setTitle($title)
            ->setKeywords($request->get('keywords'))
            ->setDescription($request->get('description'))
            ->setIntroduction($request->get('introduction'))
            ->setContent($content)
            ->setIsPublished($request->get('is_published', false) == 'true' ? true : false)
            ->setParent($request->get('parent', 0))
            ->setIsDeleted(false)
            ->setCreateBy($this->get('security.token_storage')->getToken()->getUser()->getId())
            ->setDatecreate(new \DateTime());

        try {
            if (null !== $id) {
                $service->update($newObject);
            } else {
                $service->create($newObject);
            }
        } catch (DBALException $e) {
            return new ErrorJsonResponse($e->getMessage());
        }

        return new ContentJsonResponse(array('status' => 'ok', 'message' => 'The operation completed successfully'));
    }

    public function ajaxSetMainAction(Request $request)
    {
        $id = $request->get('id');

        if (null === $id) {
            return new ErrorJsonResponse(sprintf('Argument \'ID\' is required!'));
        }

        $service = $this->get('cms.content.content.service');

        $currentMain = $service->findOneBy(array('is_main' => true));

        $main = $service->findOneById($id);

        if (!$main) {
            return new ErrorJsonResponse(sprintf('Content of ID \'%s\' not found!', $id));
        }

        try {
            $currentMain->setIsMain(false);
            $service->update($currentMain);

            $main->setIsMain(true);
            $service->update($main);
        } catch (DBALException $e) {
            return new ErrorJsonResponse($e->getMessage());
        }

        return new ContentJsonResponse(array('status' => 'ok', 'message' => 'The operation completed successfully'));
    }
}

Resources/views/Content/edit.html.twig
{% extends "DashboardBundle:Layout:base.html.twig" %}

{% block javascripts %}
    {{ parent() }}
    {% javascripts
    '@LocalizationBundle/Resources/public/js/localization_form.js'
    '@jquery_tinymce' %}
    <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
    <script type="text/javascript">
        tinymce.baseURL = '/bundles/core/vendor/tinymce';
        tinymce.init({
            auto_focus: true,
            plugins: [
                "advlist autolink lists link image charmap preview hr",
                "searchreplace wordcount visualblocks visualchars code fullscreen",
                "insertdatetime media nonbreaking table contextmenu directionality",
                "emoticons template paste textcolor"
            ],
            forced_root_block: "",
            force_br_newlines: true,
            force_p_newlines: false,
            image_advtab: false,
            theme: "modern",
            setup: function (editor) {
                editor.on('blur', function (e) {
                    editor.destroy();
                });
            }
        })

        $('.tinyMce').focusin(function () {
            tinymce.EditorManager.execCommand('mceAddEditor', true, this);
            tinymce.EditorManager.execCommand('mceFocus', true, this);
        });
    </script>
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    {% stylesheets "@ContentBundle/Resources/public/css/style.css" %}
    <link rel="stylesheet" href="{{ asset(asset_url) }}">
    {% endstylesheets %}
{% endblock %}

{% block body %}
    {% embed 'ContentBundle::main.html.twig' %}
        {% block main %}
            <div class="row">
                {% form_theme form 'ContentBundle::fields.html.twig' %}
                <div class="col-md-12" ng-app="ContentBundle" ng-controller="editContent">
                    {{ form_start(form, {'method': 'POST', 'attr': {'class': 'form-horizontal'}}) }}
                        <div class="row">
                            <div class="col-md-12">
                                {{ show_locale_tabs() }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                {{ form_errors(form) }}
                                {{ form_row(form.title) }}
                                {{ form_rest(form) }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="well well-sm text-right">
                                    <input type="submit" class="btn btn-primary btn-sm" data-loading-text="Saving..."
                                           value="{{ 'Save'|trans({}, 'systems') }}"/>
                                    <a href="javascript:history.go(-1)"
                                       class="btn btn-default btn-sm">{{ 'Cancel'|trans({}, 'systems') }}</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        {% endblock %}
    {% endembed %}
{% endblock %}

Resources/views/Content/list.html.twig
{% extends "DashboardBundle:Layout:base.html.twig" %}

{% block title %}{{ parent() }} - {{ 'Content list'|trans({},'messages') }}{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {% javascripts
    '@ContentBundle/Resources/public/js/tree.js' %}
    <script src="{{ asset_url }}"></script>
    {% endjavascripts %}
    <script type="text/javascript">
        $(document).ready(function () {
            $.tree({
                'routes': {
                    'set_main': 'cms_content_ajax_set_main',
                    'get_info_file': 'cms_content_ajax_get_contents',
                    'get_info_dir': 'cms_content_directories_view',
                    'change_status_file': 'cms_content_ajax_change_status',
                    'change_status_dir': 'cms_content_directories_change_status',
                    'delete_file': 'cms_content_ajax_delete',
                    'delete_dir': 'cms_content_ajax_directories_delete'
                },
                'info': '.information'
            });
        });
    </script>
{% endblock %}

{% block body %}
    {% embed 'ContentBundle::main.html.twig' %}
        {% macro chaildDir(contents, directories, parent) %}
            {% if directories|length %}
                {% for keyDir,valDir in directories %}
                    {% if parent == valDir.parent %}
                        <ol class="dir clearfix{% if not valDir.isPublished %} text-muted{% endif %}"
                            data-id="{{ valDir.id }}">
                            <div class="col-md-8">
                                <span class="glyphicon glyphicon-folder-close"></span> {{ valDir.title|locale }}
                            </div>
                            <div class="action-panel hide col-md-4 text-right">
                                <a href="{{ url('cms_content_directories_edit',{'id': valDir.id}) }}"
                                   title="{{ 'Edit'|trans({}, 'systems') }}">
                                    <span class="glyphicon glyphicon-edit"></span>
                                </a>
                                <a href="{{ url('cms_content_create',{'parent': valDir.id}) }}"
                                   title="{{ 'Create file'|trans({}, 'systems') }}">
                                    <span class="glyphicon glyphicon-file"></span>
                                </a>
                                <a href="{{ url('cms_content_directories_create',{'parent': valDir.id}) }}"
                                   title="{{ 'Create directory'|trans({}, 'systems') }}">
                                    <span class="glyphicon glyphicon-folder-close"></span>
                                </a>
                                {% if valDir.isPublished %}
                                    <a href="#" class="change-status" title="{{ 'Unpublished'|trans({}, 'systems') }}">
                                        <span class="glyphicon glyphicon-unchecked"></span>
                                    </a>
                                {% else %}
                                    <a href="#" class="change-status" title="{{ 'Published'|trans({}, 'systems') }}">
                                        <span class="glyphicon glyphicon-check"></span>
                                    </a>
                                {% endif %}
                                <a href="#" class="delete" title="{{ 'Delete'|trans({}, 'systems') }}">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </a>
                            </div>
                        </ol>
                        <ul class="hide" data-parent='{{ valDir.id }}'>
                            {{ _self.chaildDir(contents, directories, valDir.id) }}
                            {{ _self.findContent(contents, valDir.id) }}
                        </ul>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endmacro %}

        {% macro findContent(contents, parent) %}
            {% if contents|length %}
                {% for key,val in contents %}
                    {% if parent == val.parent %}
                        <ol class="file clearfix{% if not val.isPublished %} text-muted{% endif %}"
                            data-id="{{ val.id }}">
                            <div class="col-md-8 {% if val.isDeleted %} text-muted{% endif %}">
                                <span class="glyphicon {% if val.isMain %}glyphicon-home warning{% else %}glyphicon-file{% endif %}"></span> {{ (val.title)|locale }}
                            </div>
                            <div class="action-panel hide col-md-4 text-right">
                                <a href="{{ url('cms_content_edit',{'id': val.id}) }}"
                                   title="{{ 'Edit'|trans({}, 'systems') }}">
                                    <span class="glyphicon glyphicon-edit"></span>
                                </a>
                                <a href="#" title="{{ 'Set as home'|trans({}, 'systems') }}"
                                   class="set-main{% if val.isMain %} hide{% endif %}">
                                    <span class="glyphicon glyphicon-home"></span>
                                </a>
                                {% if val.isPublished %}
                                    <a href="#" class="change-status" title="{{ 'Unpublished'|trans({}, 'systems') }}">
                                        <span class="glyphicon glyphicon-unchecked"></span>
                                    </a>
                                {% else %}
                                    <a href="#" class="change-status" title="{{ 'Published'|trans({}, 'systems') }}">
                                        <span class="glyphicon glyphicon-check"></span>
                                    </a>
                                {% endif %}
                                <a href="#" class="delete" title="{{ 'Delete'|trans({}, 'systems') }}">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </a>
                            </div>
                        </ol>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endmacro %}

        {% import _self as macros %}

        {% block main %}
            <div class="row-fluid clearfix">
                <div class="col-md-7">
                    <ul class="list-unstyled tree clearfix">
                        <li class="clearfix" data-id="0">
                            <div class="col-md-8">
                                <span class="glyphicon glyphicon-folder-open"></span> {{ 'Root'|trans({}, 'systems') }}
                            </div>
                            <div class="action-panel hide col-md-4 text-right">
                                <a href="{{ url('cms_content_create',{'parent': null}) }}"
                                   title="{{ 'Create file'|trans({}, 'systems') }}">
                                    <span class="glyphicon glyphicon-file"></span>
                                </a>
                                <a href="{{ url('cms_content_directories_create',{'parent': null}) }}"
                                   title="{{ 'Create directory'|trans({}, 'systems') }}">
                                    <span class="glyphicon glyphicon-folder-close"></span>
                                </a>
                            </div>
                        </li>
                        <ul class="list-unstyled">
                            {{ macros.chaildDir(contents, directories, null) }}
                            {{ macros.findContent(contents, null) }}
                        </ul>
                    </ul>
                </div>
                <div class="col-md-5 well information">

                </div>
            </div>
        {% endblock %}
    {% endembed %}
{% endblock %}

Resources/views/Content/view.html.twig
{% extends "ContentBundle::main.html.twig" %}

{% block title_content %}
    {{ page.title }}
{% endblock %}
    
{% block main %}
    <h1>{{ page.title }}</h1>

    {% autoescape %}
    {% spaceless %}
        {{ page.content|raw }}
    {% endspaceless %}
    {% endautoescape %}
    <hr>
    <div class="row">
        <div class="span6">
            <small>{{ 'author'|trans({}, 'ContentTranslations') }}: {{ page.createBy }}</small>
        </div>
        <div class="span6 text-right">
            <small>{{ 'date_create'|trans({}, 'ContentTranslations') }}: {{ page.dataCreate|date }}</small>
            </br>
            <small>{{ 'date_update'|trans({}, 'ContentTranslations') }}: {{ page.dataUpdate|date }}</small>
        </div>
    </div>
{% endblock %}